import { createServer } from "node:http";
import { readFileSync, existsSync, createReadStream, statSync } from "node:fs";
import { extname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot=resolve(fileURLToPath(new URL("../..",import.meta.url)));
const distRoot=join(projectRoot,"frontend","dist");
function loadLocalEnv(){const path=join(projectRoot,".env");if(!existsSync(path))return;for(const line of readFileSync(path,"utf8").split(/\r?\n/)){const match=line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);if(!match||match[2].startsWith("#")||process.env[match[1]])continue;let value=match[2].trim();if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))value=value.slice(1,-1);process.env[match[1]]=value;}}
loadLocalEnv();
const port=Number(process.env.PORT||8787),host=process.env.HOST||"127.0.0.1",allowedOrigin=(process.env.PUBLIC_ORIGIN||"http://127.0.0.1:5173").replace(/\/$/,""),productionOrigin=`http://127.0.0.1:${port}`,rateBuckets=new Map();
const originAllowed=(origin)=>!origin||origin===allowedOrigin||origin===productionOrigin;
function json(res,status,body,origin=allowedOrigin){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","Access-Control-Allow-Origin":originAllowed(origin)?origin:allowedOrigin,Vary:"Origin"});res.end(JSON.stringify(body));}
function permit(ip){const now=Date.now(),recent=(rateBuckets.get(ip)||[]).filter(time=>now-time<60000);if(recent.length>=5)return false;recent.push(now);rateBuckets.set(ip,recent);return true;}
async function createWebCall(req,res){const origin=req.headers.origin||allowedOrigin;if(req.method!=="POST")return json(res,405,{error:"Method not allowed"},origin);if(!originAllowed(req.headers.origin))return json(res,403,{error:"Origin not allowed"},origin);if(!permit(req.socket.remoteAddress||"unknown"))return json(res,429,{error:"Too many call attempts. Please wait a minute."},origin);const apiKey=process.env.RETELL_API_KEY,agentId=process.env.RETELL_AGENT_ID;if(!apiKey||!agentId||apiKey.includes("your_private")||agentId.includes("your_retell"))return json(res,503,{error:"Retell is not configured on this server."},origin);try{const response=await fetch("https://api.retellai.com/v2/create-web-call",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({agent_id:agentId,metadata:{channel:"velocity_website"},retell_llm_dynamic_variables:{dealership_name:"Northstar Auto Gallery"}}),signal:AbortSignal.timeout(12000)});const call=await response.json().catch(()=>({}));if(!response.ok){console.error("Retell create-web-call failed",response.status,call?.message||call?.error||"Unknown error");return json(res,502,{error:"The voice assistant could not start. Please try again."},origin);}return json(res,200,{accessToken:call.access_token,callId:call.call_id},origin);}catch(error){console.error("Retell request error",error instanceof Error?error.message:error);return json(res,502,{error:"The voice service is temporarily unavailable."},origin);}}
const mime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".png":"image/png",".svg":"image/svg+xml",".ico":"image/x-icon"};
function serveStatic(req,res){if(!existsSync(distRoot))return json(res,404,{error:"Frontend build not found. Run npm run build first."});const pathname=decodeURIComponent(new URL(req.url,"http://localhost").pathname);let file=resolve(distRoot,`.${pathname==="/"?"/index.html":pathname}`);if(!file.startsWith(distRoot+sep)&&file!==join(distRoot,"index.html"))return json(res,403,{error:"Forbidden"});if(!existsSync(file)||statSync(file).isDirectory())file=join(distRoot,"index.html");const cache=extname(file)===".html"?"no-cache":"public, max-age=31536000, immutable";res.writeHead(200,{"Content-Type":mime[extname(file)]||"application/octet-stream","Cache-Control":cache,"X-Content-Type-Options":"nosniff","Referrer-Policy":"strict-origin-when-cross-origin","Permissions-Policy":"microphone=(self)"});createReadStream(file).pipe(res);}
const server=createServer((req,res)=>{if(req.url==="/api/health")return json(res,200,{status:"ok",retellConfigured:Boolean(process.env.RETELL_API_KEY&&process.env.RETELL_AGENT_ID)});if(req.url==="/api/retell/web-call")return void createWebCall(req,res);if(req.method==="OPTIONS"){res.writeHead(204,{"Access-Control-Allow-Origin":allowedOrigin,"Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"});return res.end();}serveStatic(req,res);});
server.listen(port,host,()=>console.log(`Velocity server listening on ${host}:${port}`));
function shutdown(){server.close(()=>process.exit(0));setTimeout(()=>process.exit(1),10000).unref();}
process.on("SIGTERM",shutdown);
process.on("SIGINT",shutdown);
